//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Application_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Job Job { get; set; }
    }
}
