//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueJobs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobsEntities2 : DbContext
    {
        public JobsEntities2()
            : base("name=JobsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Users_interests> Users_interests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WriteCV> WriteCVs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
    }
}
