//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_interests
    {
        public int Users_interests_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Interest_ID { get; set; }
    
        public virtual Interest Interest { get; set; }
        public virtual User User { get; set; }
    }
}
