//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteCV
    {
        public int WritecvID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string PreviousWork { get; set; }
        public string Email { get; set; }
        public string Skills { get; set; }
        public string Studies { get; set; }
        public string Languages { get; set; }
        public string Hobbies { get; set; }
    
        public virtual User User { get; set; }
    }
}
